%%
%% Autogenerated by Thrift Compiler (0.8.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(istanbus_types).

-include("istanbus_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('i am a dummy struct') -> undefined.

struct_info_ext('i am a dummy struct') -> undefined.

