%%
%% Autogenerated by Thrift Compiler (0.9.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(istanbusJavaService_thrift).
-behaviour(thrift_service).


-include("istanbusJavaService_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info('i am a dummy struct') -> undefined.
%%% interface
% recommend(This, From_stop, To_stop)
function_info('recommend', params_type) ->
  {struct, [{1, string},
          {2, string}]}
;
function_info('recommend', reply_type) ->
  string;
function_info('recommend', exceptions) ->
  {struct, []}
;
% stop_search(This, Keyword)
function_info('stop_search', params_type) ->
  {struct, [{1, string}]}
;
function_info('stop_search', reply_type) ->
  string;
function_info('stop_search', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> no_function.

